apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pipe-dockerfile
  name: app-dockerfile
  annotations: {}
spec:
  selector:
    matchLabels:
      app: name
  replicas: 1
  template:
    metadata:
      labels:
        app: name
    spec:
      containers:
        - name: container
          image: >-
            quay.io/egoncalv/pipe-dockerfile:latest
          ports:
            - containerPort: 80
              protocol: TCP
          env: []
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
